import Head from 'next/head'
import sendgrid from '@sendgrid/mail';

sendgrid.setApiKey(process.env.SENDGRID_API_KEY);

// export default async (req, res) => {
//   try {
//     await sendgrid.send({
//       to: 'egriboz@gmail.com',
//       from: 'egriboz@gmail.com',
//       subject: 'Serverless Functions',
//       text: 'Hello, world!'
//     });
//   } catch (error) {
//     return res.status(error.statusCode || 500).json({ error: error.message });
//   }

//   return res.status(200).json({ error: '' });
// };

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Form
        </h1>

      </main>

      <footer>
        footer
      </footer>
    </>
  )
}
